In [2]:
import pandas as pd

csv_path = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_language_model_multichoice_inference_4_all_permutation/eval_results.csv"

In [3]:
data = pd.read_csv(csv_path)

In [4]:
data

             A          B          C          D
0    -3.696050  12.691301  -3.805767   0.236379
1    20.982216   4.055378  14.769336   7.938748
2    -9.005961   3.091261  -8.849982  -6.283132
3   -15.916595 -21.625217  -3.402817 -18.438993
4    37.286510  29.241186  23.662573  25.635937
..         ...        ...        ...        ...
847   6.909821   5.128681   1.968303   6.400368
848   3.128703   0.238101   1.915658   6.920540
849  -7.070777   1.980687 -13.108232 -11.754869
850   5.301341   3.859221  19.680168   1.964219
851  16.823912  18.754770  14.464167  34.916809

[852 rows x 4 columns]

In [7]:
max_index = []
for i in range(len(data)):
    # max_index.append(data.iloc[i, 1:].idxmax())
    # print(data.iloc[i, 1:].idxmax())
    # break
    score = data.iloc[i,i+1]
    print(score)

    break

# max_index

12.691301345825195

In [5]:
output_csv = pd.DataFrame()
output_csv['ID'] = [f'TEST_{i:03}' for i in range(len(max_index))]
output_csv['answer'] = max_index

output_csv

           ID answer
0    TEST_000      B
1    TEST_001      C
2    TEST_002      B
3    TEST_003      C
4    TEST_004      B
..        ...    ...
847  TEST_847      D
848  TEST_848      D
849  TEST_849      B
850  TEST_850      C
851  TEST_851      D

[852 rows x 2 columns]

In [6]:
output_csv.to_csv('/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_language_model_multichoice_inference_4_all_permutation/language_model_multichoice_5.csv', index=False)