In [6]:
import pandas as pd

csv_path = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_language_model_multichoice_inference_3_batch_64/eval_results.csv"

In [7]:
data = pd.read_csv(csv_path)

In [9]:
data

             A          B          C          D
0     2.830629   6.395661   3.486344   6.341754
1     9.225514  -6.970730  -1.595700  -6.293957
2    -2.915595   8.115647   0.154806   4.927797
3    58.938423  51.484531  51.339363  48.613911
4    36.922947  29.044060  28.246946  27.467514
..         ...        ...        ...        ...
847   3.991609   3.616007   3.747742   2.421844
848  24.325058  24.724531  27.091387  29.326805
849  -1.070941   6.049280  -4.060775   0.550869
850   9.602516  11.440001  15.642689  14.622804
851  -1.751634   1.196945  -2.625050   6.880183

[852 rows x 4 columns]

In [11]:
max_index = []
for i in range(len(data)):
    max_index.append(data.iloc[i, 1:].idxmax())

max_index

['B',
 'C',
 'B',
 'B',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'C',
 'D',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'D',
 'B',
 'D',
 'B',
 'C',
 'D',
 'C',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'D',
 'C',
 'B',
 'C',
 'C',
 'C',
 'D',
 'C',
 'B',
 'B',
 'D',
 'C',
 'C',
 'C',
 'B',
 'D',
 'C',
 'D',
 'B',
 'C',
 'C',
 'B',
 'D',
 'B',
 'C',
 'C',
 'D',
 'C',
 'B',
 'B',
 'C',
 'C',
 'B',
 'D',
 'C',
 'D',
 'B',
 'C',
 'B',
 'D',
 'B',
 'C',
 'D',
 'C',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'B',
 'B',
 'D',
 'B',
 'D',
 'C',
 'C',
 'C',
 'C',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'D',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'D',
 'D',
 'B',
 'D',
 'C',
 'D',
 'D',
 'C',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'C',
 'D',
 'D',
 'D',
 'C',
 'B',
 'B',
 'C',
 'C',
 'B',
 'C',
 'D',
 'D',
 'D',
 'C',
 'D',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'C',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'B',
 'D',
 'D',
 'D',
 'D',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'C',
 'D',
 'D',
 'B',
 'D',
 'C',
 'D',
 'D',
 'D',
 'C',
 'D',
 'C',
 'B',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'B',
 'C',
 'D',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'C',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'D',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'B',
 'D',
 'C',
 'C',
 'D',
 'B',
 'C',
 'B',
 'C',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'D',
 'D',
 'C',
 'B',
 'D',
 'B',
 'D',
 'B',
 'D',
 'B',
 'D',
 'C',
 'C',
 'B',
 'C',
 'B',
 'D',
 'D',
 'B',
 'B',
 'C',
 'C',
 'C',
 'B',
 'B',
 'C',
 'D',
 'B',
 'C',
 'C',
 'B',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'D',
 'C',
 'C',
 'C',
 'B',
 'D',
 'D',
 'D',
 'D',
 'D',
 'C',
 'D',
 'C',
 'B',
 'D',
 'B',
 'D',
 'C',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'C',
 'D',
 'B',
 'D',
 'C',
 'C',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'B',
 'C',
 'B',
 'D',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'C',
 'D',
 'D',
 'C',
 'B',
 'D',
 'D',
 'C',
 'B',
 'D',
 'D',
 'D',
 'D',
 'B',
 'B',
 'B',
 'D',
 'B',
 'D',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'D',
 'D',
 'C',
 'D',
 'C',
 'D',
 'B',
 'C',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'D',
 'C',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'B',
 'B',
 'D',
 'D',
 'B',
 'D',
 'C',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'B',
 'C',
 'D',
 'B',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'B',
 'C',
 'B',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'C',
 'D',
 'D',
 'B',
 'D',
 'C',
 'C',
 'D',
 'D',
 'B',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'D',
 'D',
 'C',
 'B',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'D',
 'D',
 'C',
 'B',
 'C',
 'C',
 'C',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'D',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'D',
 'C',
 'D',
 'B',
 'D',
 'C',
 'C',
 'D',
 'D',
 'C',
 'D',
 'D',
 'D',
 'B',
 'C',
 'C',
 'D',
 'B',
 'B',
 'B',
 'D',
 'B',
 'D',
 'B',
 'B',
 'B',
 'B',
 'D',
 'C',
 'C',
 'B',
 'B',
 'B',
 'C',
 'C',
 'C',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'C',
 'D',
 'B',
 'D',
 'D',
 'C',
 'B',
 'B',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'D',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'B',
 'B',
 'B',
 'D',
 'C',
 'C',
 'B',
 'B',
 'D',
 'C',
 'B',
 'C',
 'D',
 'C',
 'D',
 'C',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'C',
 'B',
 'B',
 'C',
 'D',
 'B',
 'C',
 'C',
 'D',
 'C',
 'C',
 'D',
 'D',
 'C',
 'B',
 'D',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'C',
 'C',
 'D',
 'D',
 'B',
 'C',
 'D',
 'B',
 'C',
 'D',
 'C',
 'D',
 'B',
 'D',
 'D',
 'B',
 'B',
 'D',
 'B',
 'C',
 'C',
 'D',
 'D',
 'C',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'D',
 'D',
 'D',
 'C',
 'D',
 'C',
 'C',
 'C',
 'C',
 'D',
 'C',
 'D',
 'D',
 'C',
 'B',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'B',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'D',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'C',
 'B',
 'D',
 'B',
 'C',
 'D',
 'D',
 'C',
 'C',
 'D',
 'C',
 'B',
 'D',
 'B',
 'D',
 'B',
 'C',
 'C',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'D',
 'D',
 'C',
 'D',
 'C',
 'B',
 'D',
 'B',
 'B',
 'D',
 'D',
 'C',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'C',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'C',
 'C',
 'B',
 'D',
 'B',
 'D',
 'C',
 'B',
 'B',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'C',
 'D',
 'D',
 'C',
 'D',
 'D',
 'B',
 'D',
 'C',
 'C',
 'D',
 'D',
 'C',
 'C',
 'B',
 'C',
 'B',
 'C',
 'D',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'C',
 'B',
 'C',
 'B',
 'D',
 'D',
 'D',
 'C',
 'D',
 'B',
 'C',
 'D']

In [13]:
output_csv = pd.DataFrame()
output_csv['ID'] = [f'TEST_{i:03}' for i in range(len(max_index))]
output_csv['answer'] = max_index

output_csv

           ID answer
0    TEST_000      B
1    TEST_001      C
2    TEST_002      B
3    TEST_003      B
4    TEST_004      B
..        ...    ...
847  TEST_847      C
848  TEST_848      D
849  TEST_849      B
850  TEST_850      C
851  TEST_851      D

[852 rows x 2 columns]

In [14]:
output_csv.to_csv('/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_language_model_multichoice_inference_3_batch_64/language_model_multichoice_5.csv', index=False)