In [ ]:
import pandas as pd

csv_path = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_language_model_multichoice_inference_1/eval_results-5.csv"

In [2]:
data = pd.read_csv(csv_path)

In [3]:
data

             A          B          C          D
0    -2.370243   3.976212   2.667885  -5.826669
1    -2.054683 -28.958189 -17.584164 -25.970062
2    -2.786414  16.923330   1.954083   8.757920
3    38.103821  21.330654  25.994488  22.155046
4    27.088699  17.964594  16.655251  16.809710
..         ...        ...        ...        ...
847  12.220497  -0.344577   7.099369   6.803659
848  48.580853  51.519707  48.309845  50.414307
849  -5.040473   5.195907  -5.838876  -0.297222
850  25.270714  28.087189  26.000660  36.014885
851  -5.657624   0.278055  -8.069689  14.665610

[852 rows x 4 columns]

In [8]:
max_index = []
for i in range(len(data)):
    max_index.append(data.iloc[i, 1:].idxmax())

max_index

['B',
 'C',
 'B',
 'C',
 'B',
 'D',
 'B',
 'D',
 'D',
 'C',
 'B',
 'B',
 'D',
 'B',
 'D',
 'B',
 'B',
 'C',
 'D',
 'C',
 'D',
 'C',
 'C',
 'D',
 'B',
 'B',
 'B',
 'C',
 'C',
 'D',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'C',
 'B',
 'D',
 'C',
 'B',
 'B',
 'D',
 'C',
 'B',
 'C',
 'B',
 'D',
 'C',
 'D',
 'C',
 'C',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'B',
 'C',
 'D',
 'B',
 'C',
 'C',
 'B',
 'D',
 'C',
 'D',
 'B',
 'C',
 'B',
 'D',
 'B',
 'C',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'B',
 'C',
 'C',
 'D',
 'B',
 'D',
 'B',
 'D',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'D',
 'D',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'D',
 'C',
 'B',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'B',
 'C',
 'D',
 'D',
 'B',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'D',
 'C',
 'B',
 'B',
 'C',
 'C',
 'D',
 'C',
 'D',
 'B',
 'C',
 'C',
 'D',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'C',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'D',
 'C',
 'D',
 'D',
 'D',
 'B',
 'B',
 'C',
 'B',
 'D',
 'D',
 'D',
 'D',
 'B',
 'D',
 'C',
 'C',
 'D',
 'D',
 'C',
 'D',
 'C',
 'B',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'C',
 'C',
 'C',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'B',
 'D',
 'B',
 'D',
 'B',
 'B',
 'B',
 'B',
 'D',
 'C',
 'D',
 'D',
 'D',
 'B',
 'B',
 'D',
 'D',
 'C',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'D',
 'D',
 'B',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'C',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'B',
 'B',
 'B',
 'C',
 'C',
 'D',
 'C',
 'C',
 'B',
 'B',
 'D',
 'D',
 'B',
 'B',
 'B',
 'D',
 'B',
 'C',
 'B',
 'C',
 'B',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'D',
 'B',
 'C',
 'D',
 'B',
 'C',
 'C',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'D',
 'D',
 'B',
 'C',
 'B',
 'D',
 'C',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'D',
 'D',
 'D',
 'B',
 'B',
 'C',
 'C',
 'B',
 'D',
 'B',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'D',
 'B',
 'B',
 'D',
 'D',
 'B',
 'C',
 'C',
 'D',
 'B',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'B',
 'B',
 'D',
 'D',
 'D',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'D',
 'B',
 'C',
 'B',
 'C',
 'C',
 'D',
 'B',
 'C',
 'C',
 'B',
 'D',
 'C',
 'B',
 'D',
 'D',
 'B',
 'D',
 'B',
 'B',
 'B',
 'D',
 'C',
 'D',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'D',
 'C',
 'D',
 'D',
 'C',
 'B',
 'C',
 'C',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'D',
 'C',
 'B',
 'D',
 'B',
 'D',
 'C',
 'B',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D',
 'C',
 'B',
 'B',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'C',
 'B',
 'D',
 'B',
 'C',
 'D',
 'B',
 'B',
 'D',
 'B',
 'C',
 'B',
 'C',
 'B',
 'C',
 'C',
 'B',
 'D',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'D',
 'B',
 'B',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'B',
 'C',
 'B',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'C',
 'B',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'D',
 'C',
 'B',
 'D',
 'C',
 'D',
 'B',
 'B',
 'B',
 'D',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'C',
 'C',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D',
 'D',
 'B',
 'D',
 'D',
 'C',
 'B',
 'D',
 'D',
 'C',
 'B',
 'D',
 'D',
 'B',
 'D',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'B',
 'D',
 'B',
 'C',
 'C',
 'C',
 'B',
 'B',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'D',
 'D',
 'B',
 'D',
 'D',
 'B',
 'C',
 'C',
 'D',
 'B',
 'C',
 'B',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'D',
 'B',
 'B',
 'C',
 'C',
 'B',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'C',
 'D',
 'D',
 'C',
 'D',
 'B',
 'B',
 'B',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'B',
 'B',
 'B',
 'D',
 'C',
 'C',
 'D',
 'C',
 'D',
 'C',
 'B',
 'D',
 'C',
 'B',
 'B',
 'D',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'B',
 'C',
 'C',
 'D',
 'C',
 'D',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'B',
 'C',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'B',
 'B',
 'D',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'C',
 'B',
 'D',
 'D',
 'B',
 'B',
 'C',
 'C',
 'B',
 'C',
 'B',
 'B',
 'B',
 'D',
 'D',
 'C',
 'C',
 'B',
 'C',
 'D',
 'C',
 'C',
 'B',
 'D',
 'B',
 'B',
 'D',
 'D',
 'C',
 'B',
 'C',
 'C',
 'D',
 'D',
 'D',
 'C',
 'B',
 'C',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'C',
 'D',
 'C',
 'D',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'C',
 'B',
 'B',
 'B',
 'D',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'D',
 'B',
 'B',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D']

In [13]:
output_csv = pd.DataFrame()
output_csv['ID'] = [f'TEST_{i:03}' for i in range(len(max_index))]
output_csv['answer'] = max_index

output_csv

           ID answer
0    TEST_000      B
1    TEST_001      C
2    TEST_002      B
3    TEST_003      C
4    TEST_004      B
..        ...    ...
847  TEST_847      C
848  TEST_848      B
849  TEST_849      B
850  TEST_850      D
851  TEST_851      D

[852 rows x 2 columns]

In [14]:
output_csv.to_csv('/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_language_model_multichoice_inference_1/language_model_multichoice-10.csv', index=False)