In [2]:
import pandas as pd

csv_path = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_language_model_multichoice_inference_2_random/eval_results_9.csv"

In [3]:
data = pd.read_csv(csv_path)

In [4]:
data

             A          B          C          D
0     4.720639   9.350434   0.852592  -2.934534
1     0.769230 -31.117098 -19.297024 -22.096312
2    -1.944862  13.759081   3.365214   5.169870
3    46.539913  38.412281  39.990879  29.838285
4    55.028660  34.773212  38.666584  31.160305
..         ...        ...        ...        ...
847  30.759296  23.814056  23.090441  23.237673
848  73.209175  69.222137  64.344994  68.369064
849 -11.600032   0.608130 -11.601845 -12.374215
850  34.781380  38.425438  43.886265  43.177094
851  -7.881142   2.972877  -6.447567  11.700978

[852 rows x 4 columns]

In [5]:
max_index = []
for i in range(len(data)):
    max_index.append(data.iloc[i, 1:].idxmax())

max_index

['B',
 'C',
 'B',
 'C',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'B',
 'C',
 'D',
 'C',
 'D',
 'C',
 'C',
 'D',
 'B',
 'B',
 'B',
 'C',
 'C',
 'C',
 'B',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'B',
 'C',
 'C',
 'B',
 'B',
 'C',
 'B',
 'B',
 'D',
 'C',
 'B',
 'C',
 'B',
 'D',
 'C',
 'B',
 'C',
 'C',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'C',
 'B',
 'B',
 'B',
 'C',
 'B',
 'D',
 'C',
 'D',
 'C',
 'D',
 'B',
 'D',
 'B',
 'C',
 'D',
 'C',
 'C',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'D',
 'B',
 'C',
 'C',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'C',
 'D',
 'B',
 'D',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'D',
 'C',
 'B',
 'D',
 'C',
 'C',
 'C',
 'B',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'B',
 'C',
 'D',
 'D',
 'B',
 'C',
 'D',
 'B',
 'B',
 'D',
 'D',
 'D',
 'C',
 'B',
 'B',
 'C',
 'C',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'D',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'C',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'D',
 'D',
 'D',
 'D',
 'D',
 'B',
 'B',
 'C',
 'B',
 'D',
 'D',
 'D',
 'D',
 'B',
 'D',
 'C',
 'C',
 'D',
 'D',
 'C',
 'D',
 'C',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'D',
 'D',
 'C',
 'B',
 'B',
 'B',
 'C',
 'C',
 'C',
 'C',
 'B',
 'D',
 'B',
 'C',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'B',
 'C',
 'B',
 'D',
 'D',
 'B',
 'B',
 'B',
 'D',
 'C',
 'D',
 'D',
 'D',
 'C',
 'D',
 'D',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'D',
 'D',
 'C',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'C',
 'D',
 'D',
 'C',
 'D',
 'B',
 'D',
 'B',
 'B',
 'B',
 'D',
 'C',
 'D',
 'D',
 'D',
 'B',
 'B',
 'B',
 'D',
 'B',
 'B',
 'B',
 'D',
 'C',
 'C',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'C',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'D',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'C',
 'B',
 'C',
 'D',
 'B',
 'B',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'C',
 'B',
 'D',
 'B',
 'D',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'B',
 'D',
 'B',
 'B',
 'C',
 'C',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'B',
 'D',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'D',
 'B',
 'C',
 'B',
 'C',
 'C',
 'D',
 'B',
 'C',
 'C',
 'B',
 'B',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'D',
 'C',
 'D',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'B',
 'B',
 'C',
 'D',
 'C',
 'C',
 'C',
 'C',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D',
 'D',
 'C',
 'B',
 'D',
 'B',
 'D',
 'C',
 'B',
 'C',
 'B',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D',
 'B',
 'B',
 'C',
 'D',
 'B',
 'D',
 'B',
 'C',
 'B',
 'D',
 'D',
 'C',
 'B',
 'D',
 'C',
 'B',
 'D',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'B',
 'B',
 'B',
 'C',
 'B',
 'C',
 'C',
 'B',
 'D',
 'B',
 'C',
 'B',
 'C',
 'D',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D',
 'B',
 'C',
 'D',
 'C',
 'B',
 'C',
 'B',
 'D',
 'C',
 'D',
 'D',
 'D',
 'B',
 'C',
 'C',
 'B',
 'D',
 'C',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'D',
 'B',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'D',
 'C',
 'B',
 'B',
 'D',
 'C',
 'C',
 'D',
 'D',
 'C',
 'D',
 'D',
 'C',
 'B',
 'C',
 'C',
 'D',
 'C',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'C',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'D',
 'D',
 'B',
 'D',
 'D',
 'C',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'B',
 'D',
 'D',
 'B',
 'B',
 'D',
 'C',
 'B',
 'B',
 'B',
 'B',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'C',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'C',
 'D',
 'C',
 'D',
 'D',
 'B',
 'C',
 'C',
 'D',
 'C',
 'C',
 'B',
 'D',
 'B',
 'B',
 'D',
 'B',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'B',
 'B',
 'C',
 'C',
 'B',
 'D',
 'D',
 'B',
 'C',
 'B',
 'D',
 'C',
 'B',
 'D',
 'D',
 'D',
 'B',
 'C',
 'B',
 'D',
 'D',
 'C',
 'D',
 'B',
 'B',
 'B',
 'B',
 'B',
 'D',
 'C',
 'D',
 'D',
 'C',
 'D',
 'D',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'C',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'B',
 'B',
 'D',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'B',
 'D',
 'D',
 'D',
 'B',
 'D',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'C',
 'B',
 'B',
 'B',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'C',
 'B',
 'D',
 'D',
 'B',
 'B',
 'C',
 'C',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'D',
 'C',
 'C',
 'B',
 'C',
 'D',
 'D',
 'B',
 'B',
 'D',
 'B',
 'B',
 'B',
 'D',
 'C',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'B',
 'B',
 'C',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'D',
 'D',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'B',
 'B',
 'D',
 'C',
 'D',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'D',
 'C',
 'B',
 'C',
 'B',
 'C',
 'C',
 'D',
 'B',
 'B',
 'C',
 'D',
 'B',
 'B',
 'C',
 'D',
 'D',
 'D',
 'B',
 'C',
 'D',
 'B',
 'B',
 'B',
 'C',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'B',
 'C',
 'B',
 'D',
 'D',
 'D',
 'C',
 'C',
 'C',
 'C',
 'B',
 'D',
 'B',
 'D',
 'D',
 'D',
 'B',
 'B',
 'B',
 'C',
 'D']

In [6]:
output_csv = pd.DataFrame()
output_csv['ID'] = [f'TEST_{i:03}' for i in range(len(max_index))]
output_csv['answer'] = max_index

output_csv

           ID answer
0    TEST_000      B
1    TEST_001      C
2    TEST_002      B
3    TEST_003      C
4    TEST_004      C
..        ...    ...
847  TEST_847      B
848  TEST_848      B
849  TEST_849      B
850  TEST_850      C
851  TEST_851      D

[852 rows x 2 columns]

In [7]:
output_csv.to_csv('/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_language_model_multichoice_inference_3_batch_128/language_model_multichoice_5.csv', index=False)